apiVersion: v1
kind: Service
metadata:
  labels:
    component: angular-app 
  name: angular-app-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - name: service-port-name
    port: 80
    protocol: TCP
  selector:
    component: angular-app